### ISSUE TITLE
TypeError: process.send is not a function

### ISSUE THREAD

**Issue by vimal-hoh** [varunkumar/webrtc-node#2]
/home/vimal2/programs/webrtc-examples/webrtc-node/app.js:46
  process.send('online');
          ^

TypeError: process.send is not a function
    at Server.<anonymous> (/home/vimal2/programs/webrtc-examples/webrtc-node/app.js:46:11)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1257:10)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickCallback (node.js:353:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by nagarjunac** [comment]
Hi Vimal, I am facing the same issue. Any luck ?

**Comment by varunkumar** [comment]
You have to use [naught](https://github.com/andrewrk/naught) for starting the server. `naught start app.js`
